LICENSE.txt, README.md
- Add `MIT` license
- Update project shields.
=> chore: add license and update shields

README.md, seed/avatar.ts
=> fix: fix typos

package.json, src/server-rest.ts
- add CORS to REST server config
=> fix: add cors to rest api

package-lock.json
- run `npm audit fix` to fix security issues.
=> chore(deps): bump dependencies to fix security issues

README.md
* Adds a couple of prerequisites 
* Makes readme more structured
=> docs: guidance with links and structured setup

src/rest/controllers/Heroes.ts
- eliminate the problem with updating the description field hero model
```"PUT method (rest API) for updating hero data needs fixes - you can update everything BUT description"```
=> fix: eliminate problem with updating description field in hero model [PUT request]

src/rest/controllers/Heroes.ts, src/utils/fragments.ts
- Introduce changes from `develop` to `QA`.
=> Develop -> QA

src/rest/controllers/Heroes.ts
- add type field to the PUT `/heroes/:id` request response
=> fix: add type field to the PUT request response

src/rest/controllers/Heroes.ts, src/server-rest.ts
- Add endpoint returning random hero from the all heroes list.
=> feat: add get random hero endpoint

.gitignore, src/graphql/Avatar/avatar-mutation.ts, src/graphql/Avatar/avatar-query.ts, src/graphql/Avatar/avatar-schema.graphql, src/graphql/Hero/hero-custom.ts, src/graphql/Hero/hero-mutation.ts, src/graphql/Hero/hero-query.ts, src/graphql/Type/type-mutation.ts, src/graphql/Type/type-query.ts, src/rest/controllers/Avatars.ts, src/rest/controllers/Heroes.ts, src/rest/controllers/Types.ts, src/server-graphql.ts, src/server-rest.ts, tsconfig.json
=> Fixed types, imports

README.md
https://netguru.atlassian.net/browse/FA-157
- Set new Heroes API icon
=> [Fix/FA-157] - Set new Heroes API icon

README.md, src/rest/controllers/Heroes.ts
- no ticket
- Introduce changes from Develop to Master
=> Develop -> Master

src/graphql/Avatar/avatar-mutation.ts, src/graphql/Hero/hero-mutation.ts, src/graphql/Type/type-mutation.ts, src/rest/controllers/Avatars.ts, src/rest/controllers/Heroes.ts, src/rest/controllers/Types.ts, src/server-graphql.ts, src/types/prisma.ts
https://netguru.atlassian.net/browse/FA-XXX
- Add total count field to the /heroes endpoint
- clean up imports
=> [Feature/FA-166] - Add total count field to the /heroes endpoint [REST]

src/graphql/Hero/hero-query.ts, src/graphql/Hero/hero-schema.graphql
https://netguru.atlassian.net/browse/FA-167
- Add total count field to the GraphQL heroes query
=> [Feature/FA-167] - Add total count field to the GraphQL heroes query

README.md
https://netguru.atlassian.net/browse/FA-XXX
Add the missing first step to `Initial setup`: **clone this repo**
=> docs: add missing clone this repo initial setup step

package-lock.json, package.json
https://netguru.atlassian.net/browse/FA-238
Vulnerable packages are audited and updated
=> chore: npm audit

src/rest/controllers/Heroes.ts, src/utils/error-handler.ts
https://netguru.atlassian.net/browse/FA-251
- Improve error code & expect all fields in POST and PUT methods
Screens for `POST` endpoint. For `PUT` one happens the same (the same logic under the hood):
00" src="https://user-images.githubusercontent.com/16977412/108921927-e3f92680-7636-11eb-8078-612cdfa7e0d5.png">
=> [Feat/FA-251] - Improve error code & expect all fields in POST and PUT methods

README.md
https://netguru.atlassian.net/browse/FA-297
Add link to documentation in the README.md body
=> feat(fa-297): add documentation link to README.md content body

README.md, package-lock.json, package.json, src/graphql/Avatar/avatar-mutation.ts, src/graphql/Hero/hero-mutation.ts, src/graphql/Hero/hero-query.ts, src/graphql/Hero/hero-schema.graphql, src/graphql/Type/type-mutation.ts, src/rest/controllers/Avatars.ts, src/rest/controllers/Heroes.ts, src/rest/controllers/Types.ts, src/server-graphql.ts, src/types/prisma.ts, src/utils/error-handler.ts
New version of Heroes API is coming (see by https://github.com/netguru/heroes-api/pull/74) and we want to keep old API for some reason.
=> Merge: align api-v1.0 with master

prisma/schema.prisma
- Allows to store longer descriptions on Hero model
=> feat: allow longer descriptions

prisma/seeds/heroes.seed.ts
- Changes avatar paths to correct one.
=> fix: change assets path to correct /static path
